pipeline:
  label: example
  estimator: Pipeline
  estimator_pkg: sklearn.pipeline
  estimator_params:
    steps:
      - label: print-entry-data
        estimator: Sentinel
        estimator_pkg: tictacs.wrappers
      - label: union
        estimator: FeatureUnion
        estimator_pkg: sklearn.pipeline
        estimator_params:
          n_jobs: 1
          transformer_list: 
            - label: count words
              estimator: CountVectorizer
              estimator_pkg: sklearn.feature_extraction.text
              estimator_params:
                max_features: 100
            - label: count 3grams tfidf
              estimator: TfidfVectorizer
              estimator_pkg: sklearn.feature_extraction.text
              estimator_params:
                analyzer: word
      - label: print-classifier-input
        estimator: Sentinel
        estimator_pkg: tictacs.wrappers
        estimator_params:
          # only print first row of classifier input
          # other options can be disabled if you like
          x: 1
          # change y to number to see specific element
          y: null
          # change shape to False if you don't want it printed
          shape: True
          # change py_type to False if you don't want it printed
          py_type: True
      - label: svm
        estimator: LinearSVC
        estimator_pkg: sklearn.svm
        estimator_params:
        # if no parameters need to be passed, we needn't specify the key
        # estimator_params - it is populated with an empty dictionary
